### PR TITLE
SLING-12070: migrate to jakarta.json

### PR DESCRIPTION
**Pull request by apelluru**

### CODE REVIEW

**Review by rombert — COMMENTED** [review]
Are there technical blockers to keeping Java 8 compatibility?

**Comment by apelluru** [comment]
> Are there technical blockers to keeping Java 8 compatibility?

@rombert Yes, we do. This is due to the latest version of the maven-compiler-plugin, which mandates Java 11 as the target version.

[Jenkins job](https://ci-builds.apache.org/job/Sling/job/modules/job/sling-org-apache-sling-xss/view/change-requests/job/PR-35/2/console)

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project org.apache.sling.xss: Fatal error compiling: invalid target release: 11 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project org.apache.sling.xss: Fatal error compiling`

**Comment by rombert** [comment]
> > Are there technical blockers to keeping Java 8 compatibility?
> 
> @rombert Yes, we do. This is due to the latest version of the maven-compiler-plugin, which mandates Java 11 as the target version.
> 
> [Jenkins job](https://ci-builds.apache.org/job/Sling/job/modules/job/sling-org-apache-sling-xss/view/change-requests/job/PR-35/2/console)
> 
> `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project org.apache.sling.xss: Fatal error compiling: invalid target release: 11 -> [Help 1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project org.apache.sling.xss: Fatal error compiling`

Right, that happens because you removed the `sling.java.version` property that was defaulting to 8.

**Review by rombert — APPROVED** [review]
LGTM, thanks.

**Comment by apelluru** [comment]
> LGTM, thanks.

Hi @rombert 

Is it known issue?

https://ci-builds.apache.org/job/Sling/job/modules/job/sling-org-apache-sling-xss/job/master/218/console

```[Pipeline] isUnix
[Pipeline] sh
+ mvn -U -B -e clean compile
/home/jenkins/jenkins-agent/workspace/ling-org-apache-sling-xss_master@tmp/durable-378778c7/script.sh: 1: /home/jenkins/jenkins-agent/workspace/ling-org-apache-sling-xss_master@tmp/durable-378778c7/script.sh: mvn: not found
[Pipeline] }
[Pipeline] // withMaven```

**Comment by rombert** [comment]
@apelluru - yes, fallout from https://issues.apache.org/jira/browse/INFRA-25083, should be fixed now.

**Pull request merged**
