### PR TITLE
SLING-12116 - Update transative guava dependency to version 32.1.3-jre 

### PR DESCRIPTION
**Pull request by nonanalou**

### CODE REVIEW

**Comment by rombert** [comment]
@nonanalou - thanks for the PR. Can you please create a SLING jira explaining the need for an update?

**Comment by nonanalou** [comment]
[SLING-12116](https://issues.apache.org/jira/browse/SLING-12116) - Update transative guava dependency to version 32.1.3-jre

**Comment by rombert** [comment]
The build fails because of a Java 8 check

> [ERROR] /home/robert/sources/apache/sling/org-apache-sling-xss/target/classes/com/google/common/hash/Hashing$Crc32cMethodHandles.class:512: Undefined reference: java.util.zip.Checksum java.lang.invoke.MethodHandle.invokeExact()

According to https://github.com/google/guava/wiki/Compatibility, Guava officially supports Java 8. I wonder if this is a false issue.

**Comment by rombert** [comment]
PR applied, thanks @nonanalou for your contribution!

**Pull request merged**
