### PR TITLE
SLING-10397 - Update to Sling Bundle Parent 41

### PR DESCRIPTION
**Pull request by rombert**

### CODE REVIEW

**Comment by rombert** [comment]
@raducotescu @kwin - The Sling XSS build fails with the latest parent pom, presumably due to [SLING-10170](https://issues.apache.org/jira/browse/SLING-10170). Suggestions on how to fix? We could pin the animal-sniffer-maven-plugin to an older version, but I think it would be better to have a proper fix.

**Comment by raducotescu** [comment]
I cannot reproduce this locally. Is there something special that I need to do besides running `mvn clean verify`?

**Comment by kwin** [comment]
I can reproduce locally when building with a JDK8 (@raducotescu animal-sniffer is not used when using JDK9 or newer, as the release option for javac is sufficient in that case, https://github.com/apache/sling-parent/blob/dc0a5b0c417627edeecf3f2ca6e2af647d29a55b/sling-parent/pom.xml#L541). Looks like some classpath issue, investigating now...

**Comment by kwin** [comment]
This happens, because the phase of the animal-sniffer-m-p changed in 1.19+ (https://github.com/mojohaus/animal-sniffer/commit/6363af4e07240f6240e9cfd4d2e35fecbe6f41ca#diff-600eed5a54fef6581f6ed4ff10c0bb63143255964d046e9ed3ff524337f9846cR64) from PROCESS_CLASSES to PROCESS_TEST_CLASSES. This leads to the fact that the classes being embedded (i.e. the ones from OWASP) are now checked as well, which fails due to the incomplete compile classpath. Just executing animal-sniffer-maven-plugin prior to bnd-maven-plugin would work (but only if combined with `clean`). The safer approach is to exclude those embedded classes from sniffing....

**Comment by raducotescu** [comment]
Thanks for the fix, @kwin. Question - how come that now `bnd` automatically embeds the dependencies?

**Comment by kwin** [comment]
>  now bnd automatically embeds the dependencies?

That has always been like that AFAIK. Compare with https://groups.google.com/g/bndtools-users/c/NAdU0_X8OKY.

**Comment by raducotescu** [comment]
But we're not using conditional packages and I remember we had this discussion a while back, specifically about this bundle - https://lists.apache.org/thread.html/d8699debe3438159ae275f5c5c27ec7d2aa7c65cefb4b334033c7c7b%40%3Cdev.sling.apache.org%3E.

**Comment by kwin** [comment]
Private-Package behaves the same: https://bnd.bndtools.org/heads/private_package.html

**Comment by raducotescu** [comment]
AHA! The mysterious ways of `bnd`. Thanks for the hint!

**Comment by raducotescu** [comment]
It seems however that the bundle doesn't correctly embed what we had before:
```
ERROR : bundle org.apache.sling.xss:2.2.13.SNAPSHOT (138)[org.apache.sling.xss.impl.XSSFilterImpl(514)] : The activate method has thrown an exception
java.lang.NoClassDefFoundError: org/xml/sax/SAXException
	at org.apache.sling.xss.impl.PolicyHandler.<init>(PolicyHandler.java:52)
	at org.apache.sling.xss.impl.XSSFilterImpl.updatePolicy(XSSFilterImpl.java:311)
	at org.apache.sling.xss.impl.XSSFilterImpl.activate(XSSFilterImpl.java:263)
```

**Comment by raducotescu** [comment]
I tried playing with the `Conditional-Package` header, but still some classes were not properly embedded, so I switched back to manually defining which dependencies get embedded, combined with the exclusion list for the `animal-sniffer` plugin.

**Comment by raducotescu** [comment]
@rombert, do you have an issue for this parent pom update?

**Comment by rombert** [comment]
@raducotescu - I did not create an issue for this yet, I thought this would be fire and forget :-)

**Comment by kwin** [comment]
> It seems however that the bundle doesn't correctly embed what we had before:
> 
> ```
> ERROR : bundle org.apache.sling.xss:2.2.13.SNAPSHOT (138)[org.apache.sling.xss.impl.XSSFilterImpl(514)] : The activate method has thrown an exception
> java.lang.NoClassDefFoundError: org/xml/sax/SAXException
> 	at org.apache.sling.xss.impl.PolicyHandler.<init>(PolicyHandler.java:52)
> 	at org.apache.sling.xss.impl.XSSFilterImpl.updatePolicy(XSSFilterImpl.java:311)
> 	at org.apache.sling.xss.impl.XSSFilterImpl.activate(XSSFilterImpl.java:263)
> ```

It is just that `org.xml.sax` is not mentioned as Private-Package. IMHO we should really try to clean it up, as now we do it twice. I will try to come up with a new PR.

**Comment by raducotescu** [comment]
I've tried multiple options and just decided for what you see in the last commit, since none of the other attempts were reliable. There were issues with multiple other packages (e.g. `org.w3c.dom.*`, `org.owasp.validator.html.scan`, etc.).

**Pull request merged**
