### PR TITLE
SLING-8328 - The XSSFilterImpl component cannot start on Jboss 7 deployments

### PR DESCRIPTION
**Pull request by karlpauls**

### CODE REVIEW

**Comment by rombert** [comment]
A SonarQube report for the changes added _only by this pull request_ was generated. Please review it at https://builds.apache.org/job/Sling/job/sling-org-apache-sling-xss/job/PR-5/1/artifact/target/sonar/issues-report/issues-report-light.html

**Comment by bdelacretaz** [comment]
Do the FactoryFinder classes really need to be duplicated? Instead of having a single class elsewhere from which they inherit.

Currently they're bad copies of each other, with the same code AFAICS but extra imports in one of them.

Also, it would be nice to briefly explain in SLING-8328 the rationale for this workaround, as it's a bit mysterious (at least to me ;-)

**Comment by raducotescu** [comment]
Normally the `javax.xml` package is boot delegated. However, starting with [SLING-8321](https://issues.apache.org/jira/browse/SLING-8321) we had to embed the `javax.xml` implementations provided by `xml-apis`, so that the `org.apache.sling.xss` bundle correctly works when executed on IBM's J9 JVM, which doesn't provide `org.w3c.dom.ElementTraversal` - see more explanations in that issue.

Since then, we've discovered issues with the SPI factories from `javax.xml`, since every application server provides its own implementations which are different from the ones provided by the JVMs and are also a bit different than the ones provided by the embedded `xml-apis`. The two Factories you see here are overridden versions of what's normally available in the JVMs but they make sure that the implementations being picked up at runtime for our bundle are the embedded ones, rather than the ones wired by the application servers.

Granted, the final code can and will be nicer. The PR here was the first attempt to figure out what we need to do to make the `org.apache.sling.xss` bundle work correctly on J9 (mainly when deployed on WebSphere) and Jboss.

**Comment by rombert** [comment]
Silly question - can't we stop using `org.w3c.dom.ElementTraversal` by "simply" downgrading the dependency that looks for it?

**Comment by raducotescu** [comment]
We could, if we want to reintroduce a vulnerable AntiSamy version. 😁

**Comment by rombert** [comment]
Ah, ok. I guess that's slightly sub-optimal :-)

**Comment by raducotescu** [comment]
@bdelacretaz, @karlpauls and I have thought about extracting an abstract base class for the two factories, but it wouldn't optimise anything in this situation, since both private factories are expected to be present. We'd have one class more and we could run into potential issues later, if either of the two APIs starts evolving differently.

**Comment by kwin** [comment]
Not a quick fix, but I guess we in the long run we should really switch towards java-html-sanitizer (https://issues.apache.org/jira/browse/SLING-7231) because that has less external dependencies. It is a shame that https://github.com/OWASP/java-html-sanitizer/pull/161/ has not been finished though...

**Comment by raducotescu** [comment]
I know. The only thing missing here is time.

**Comment by bdelacretaz** [comment]
> ...it wouldn't optimise anything in this situation, since both private factories are expected to be present...

@raducotescu thanks for clarifying! I'm fine with such an explanation but it's probably best to include it (or point to it) from the code comments, as that's where our future selves might be surprised to find such code duplication.

**Pull request merged**
